// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://trcuiahdaeydlaibgvtk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRyY3VpYWhkYWV5ZGxhaWJndnRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4MjQ2MTMsImV4cCI6MjA1ODQwMDYxM30.-TgyiJNEUwmyca9RnY1Ox1OvtkxQCLQqKSJBlxPb7Ik";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);